class android.os.AsyncTask$3 extends java.util.concurrent.FutureTask
{
    final android.os.AsyncTask this$0;

    void <init>(android.os.AsyncTask, java.util.concurrent.Callable)
    {
        android.os.AsyncTask$3 $r0;
        android.os.AsyncTask $r1;
        java.util.concurrent.Callable $r2;

        $r0 := @this: android.os.AsyncTask$3;

        $r1 := @parameter0: android.os.AsyncTask;

        $r2 := @parameter1: java.util.concurrent.Callable;

        $r0.<android.os.AsyncTask$3: android.os.AsyncTask this$0> = $r1;

        specialinvoke $r0.<java.util.concurrent.FutureTask: void <init>(java.util.concurrent.Callable)>($r2);

        return;
    }

    protected void done()
    {
        java.lang.Throwable $r0;
        android.os.AsyncTask$3 $r1;
        java.lang.Object $r2;
        android.os.AsyncTask$InternalHandler $r3;
        android.os.AsyncTask$AsyncTaskResult $r4;
        android.os.AsyncTask $r5;
        java.lang.Object[] $r6;
        android.os.Message $r7;
        java.lang.InterruptedException $r8;
        java.util.concurrent.ExecutionException $r9;
        java.lang.RuntimeException $r10;
        java.util.concurrent.CancellationException $r11;

        $r1 := @this: android.os.AsyncTask$3;

        $r2 = null;

     label1:
        $r2 = virtualinvoke $r1.<java.util.concurrent.FutureTask: java.lang.Object get()>();

     label2:
        $r3 = staticinvoke <android.os.AsyncTask: android.os.AsyncTask$InternalHandler access$200()>();

        $r4 = new android.os.AsyncTask$AsyncTaskResult;

        $r5 = $r1.<android.os.AsyncTask$3: android.os.AsyncTask this$0>;

        $r6 = newarray (java.lang.Object)[1];

        $r6[0] = $r2;

        specialinvoke $r4.<android.os.AsyncTask$AsyncTaskResult: void <init>(android.os.AsyncTask,java.lang.Object[])>($r5, $r6);

        $r7 = virtualinvoke $r3.<android.os.Handler: android.os.Message obtainMessage(int,java.lang.Object)>(1, $r4);

        virtualinvoke $r7.<android.os.Message: void sendToTarget()>();

        return;

     label3:
        $r8 := @caughtexception;

        staticinvoke <android.util.Log: int w(java.lang.String,java.lang.Throwable)>("AsyncTask", $r8);

        goto label2;

     label4:
        $r9 := @caughtexception;

        $r10 = new java.lang.RuntimeException;

        $r0 = virtualinvoke $r9.<java.lang.Throwable: java.lang.Throwable getCause()>();

        specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r0);

        throw $r10;

     label5:
        $r11 := @caughtexception;

        $r3 = staticinvoke <android.os.AsyncTask: android.os.AsyncTask$InternalHandler access$200()>();

        $r4 = new android.os.AsyncTask$AsyncTaskResult;

        $r5 = $r1.<android.os.AsyncTask$3: android.os.AsyncTask this$0>;

        specialinvoke $r4.<android.os.AsyncTask$AsyncTaskResult: void <init>(android.os.AsyncTask,java.lang.Object[])>($r5, null);

        $r7 = virtualinvoke $r3.<android.os.Handler: android.os.Message obtainMessage(int,java.lang.Object)>(3, $r4);

        virtualinvoke $r7.<android.os.Message: void sendToTarget()>();

        return;

     label6:
        $r0 := @caughtexception;

        $r10 = new java.lang.RuntimeException;

        specialinvoke $r10.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r0);

        throw $r10;

        catch java.lang.InterruptedException from label1 to label2 with label3;
        catch java.util.concurrent.ExecutionException from label1 to label2 with label4;
        catch java.util.concurrent.CancellationException from label1 to label2 with label5;
        catch java.lang.Throwable from label1 to label2 with label6;
    }
}
