public class com.android.internal.os.ZygoteInit$MethodAndArgsCaller extends java.lang.Exception implements java.lang.Runnable
{
    private final java.lang.String[] mArgs;
    private final java.lang.reflect.Method mMethod;

    public void <init>(java.lang.reflect.Method, java.lang.String[])
    {
        com.android.internal.os.ZygoteInit$MethodAndArgsCaller $r0;
        java.lang.reflect.Method $r1;
        java.lang.String[] $r2;

        $r0 := @this: com.android.internal.os.ZygoteInit$MethodAndArgsCaller;

        $r1 := @parameter0: java.lang.reflect.Method;

        $r2 := @parameter1: java.lang.String[];

        specialinvoke $r0.<java.lang.Exception: void <init>()>();

        $r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.reflect.Method mMethod> = $r1;

        $r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.String[] mArgs> = $r2;

        return;
    }

    public void run()
    {
        com.android.internal.os.ZygoteInit$MethodAndArgsCaller $r0;
        java.lang.String[] $r1;
        java.lang.Throwable $r2;
        java.lang.reflect.Method $r3;
        java.lang.Object[] $r4;
        java.lang.IllegalAccessException $r5;
        java.lang.RuntimeException $r6;
        java.lang.reflect.InvocationTargetException $r7;
        boolean $z0;
        java.lang.Error $r8;

        $r0 := @this: com.android.internal.os.ZygoteInit$MethodAndArgsCaller;

        $r3 = $r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.reflect.Method mMethod>;

        $r4 = newarray (java.lang.Object)[1];

        $r1 = $r0.<com.android.internal.os.ZygoteInit$MethodAndArgsCaller: java.lang.String[] mArgs>;

        $r4[0] = $r1;

     label1:
        virtualinvoke $r3.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>(null, $r4);

     label2:
        return;

     label3:
        $r5 := @caughtexception;

        $r6 = new java.lang.RuntimeException;

        specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>($r5);

        throw $r6;

     label4:
        $r7 := @caughtexception;

        $r2 = virtualinvoke $r7.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getCause()>();

        $z0 = $r2 instanceof java.lang.RuntimeException;

        if $z0 == 0 goto label5;

        $r6 = (java.lang.RuntimeException) $r2;

        throw $r6;

     label5:
        $z0 = $r2 instanceof java.lang.Error;

        if $z0 == 0 goto label6;

        $r8 = (java.lang.Error) $r2;

        throw $r8;

     label6:
        $r6 = new java.lang.RuntimeException;

        specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>($r7);

        throw $r6;

        catch java.lang.IllegalAccessException from label1 to label2 with label3;
        catch java.lang.reflect.InvocationTargetException from label1 to label2 with label4;
    }
}
